### ISSUE TITLE
Issues get protect_rmd to work

### ISSUE THREAD

**Issue by mattwarkentin** [favstats/rmdprotectr#1]
Hi @favstats,

I just stumbled upon this package and it looks cool! However, I am having some issues getting things to work. A few comments:
- The function errors when the Rmd file isn't in the current working directory and an absolute path is used, with an error like:
```r
rmdprotectr::protect_rmd("some/path/index.Rmd", pw = "pw")
```
```
Error: The directory '1a91d62f7ca67399625a4368a6ab5d4a3baa6073' does not not exist.
```

This is because the directory is being created in the working directory, and not the directory containing the Rmd file. I believe this can fixed by changing the code below to create the directory using the root of the path provided by `path`, such as with `dir.create(paste0(dirname(path), "/", folder_name))`. Some safer code might be need to handle more types of paths (e.g. relative, absolute, file only)
https://github.com/favstats/rmdprotectr/blob/3d4b3ca06579e3122d0934da0120e2415508a2ef/R/protect.R#L32-L39

- Also, like above, I think the code below should also make sure the path from `path` is used for `output_file` so all files are stored alongside the Rmd file, do you agree?
https://github.com/favstats/rmdprotectr/blob/3d4b3ca06579e3122d0934da0120e2415508a2ef/R/protect.R#L41

Lastly, even when I get it to render correctly, I keep getting told my password is incorrect. Am I doing something wrong?

**Comment by jamiecmontgomery** [comment]
Hi I am having the same issue, these are great suggestions for improving the code. 

My workflow is:
- do the Rmd in a private repository, but copy the knitted .html file to a public "reports" repo 
- using github pages, get a URL to share out the html file, ideally with password protection

**Comment by mattwarkentin** [comment]
I actually made these changes in my fork of this package. I would be happy to submit the PR if @favstats would be interested in it. Let me know.

In the meantime, @jamiecmontgomery, you are welcome to install my fork and see if it works for you:
```r
remotes::install_github("mattwarkentin/rmdprotectr")
```

**Comment by jamiecmontgomery** [comment]
Thanks I am actually using your code, still having issues with the wrong password once rendered though, have you figured that out?

**Comment by mattwarkentin** [comment]
It's been about a month since I played around with this - but I think my line of inquiry led me to believe the password doesn't work on local copies, and needs to be hosted online (i.e. via GitHub Pages). Maybe give that a shot??

**Comment by favstats** [comment]
@mattwarkentin sorry for responding very late on this!

I just checked out the changes you made in your fork and they look really great! 

Happy to accept a pull request! For me this was just a little side project but you found a lot of quirks that will make the package better when fixed! Would like to acknowledge your contributions top, what do you think is the best way to do that?
